yarnPath: .yarn/releases/yarn-4.0.2.cjs

npmPublishRegistry: "https://registry.npmjs.org"

npmRegistryServer: "https://registry.yarnpkg.com"

pnpEnableEsmLoader: true

packageExtensions:
  "ts-jest@*":
    dependencies:
      "fast-json-stable-stringify": "*"
