name: Generate packages and publish
on:
  workflow_dispatch: 
  push:
    branches:
      - main
      - release/*

permissions:
  contents: write
  
jobs:
  Build-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        with:
          fetch-depth: 0
        uses: actions/checkout@v4

      - name: Git identification
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Reset versions
        run: |
          set -x
          set -e
          git status
          git tag test-tag
          git push --follow-tags --set-upstream origin "HEAD:${{ github.ref }}"



